F08 ajouter le formulaire
stephanemalho/crazy-burger pull request #9
Opened 2023-04-16 10:41 UTC by stephanemalho

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/Admin/AdminPanel/AddForm.jsx
> +      key: Date.now(),
Pourquoi tu lui passe une key ici ?

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/Admin/AdminPanel/AddForm.jsx
> +export const EMPTY_CARD = {
vu que tu l'utilise a plusieurs endroits ca vaut peut être le coup de la mettre dans un fichier a part. (enum.js) #liveAma

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/Admin/AdminPanel/ImagePreviou.jsx
> +  const { newCard } = useContext(OrderContext);
Vu qu'il est utilisé comme un composant réutilisable tu pourrais te contenter des props. Et pour ta condition ligne 12 te limiter à si imageSource (que tu lui passe en props) est true.

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/Admin/AdminPanel/getInputTextConfig.js
> +    key: "0",
si la key a la même value que id pourquoi ne pas utiliser l'id comme value de key dans ton map où tes inputs sont appelés ?

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/Admin/AdminPanel/getInputTextConfig.js
> +export const getInputTextConfig = (newCard) => [
"newCard" attention au noms trop spécifique. Vu que c'est une config est-ce que la fonction aura forcément en paramètre une nouvelle carte ?

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/menu/Menu.jsx
> +  console.log("menu", menu);
le console.log qui traîne aha

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/main-content/menu/Menu.jsx
> +    background: #f5f5f7;
design system

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/navbar/NavBar.jsx
>          labelIfChecked={desactiver}
J'aurais tendance a dire de faire attention a mélanger les variables en anglais et francais. 
enable / desable

2023-04-16 22:05 UTC, simoncdna commented on src/components/pages/order/navbar/NavBar.jsx
>    border-radius: 10px 10px 0 0;
si on veut coller à la maquette 15px. extraRound => design system il me semble

2023-04-16 22:05 UTC, simoncdna commented on src/components/reusableUI/Card.jsx
>          <img src={imageSource} height={"100px"} width={"80px"} alt={title} />
pourquoi tu utilise sur style in line ici ?

2023-04-16 22:05 UTC, simoncdna commented on src/components/reusableUI/Card.jsx
>    background-color: white;
design system

2023-04-16 22:05 UTC, simoncdna commented on src/components/reusableUI/Card.jsx
>    border-radius: 10px;
comme pour navbar, sur la maquette 15px. extraRound => design system

2023-04-16 22:05 UTC, simoncdna commented on src/components/reusableUI/Card.jsx
> +    color: #ffa01b;
design system

2023-04-16 22:05 UTC, simoncdn commented on src/components/reusableUI/Card.jsx
> +      color: ${theme.colors.redSecondary};
Pour le feedback ici tu réutilise la couleur de base du background de l'icone il me semble. à verifier. le comportement est en vidéo je crois

2023-04-16 22:05 UTC, simoncdn commented on src/components/reusableUI/MainButton.jsx
> +function MainButton({ ButtonIcon, label, className, onClick, version = "primary" }) {
Pour le naming, je comprends ici que c'est un bouton qui est utilisé seulement dans le main. tu ne l'utilise pas de Login Form

2023-04-16 22:05 UTC, simoncdn commented on src/components/reusableUI/TextInput.jsx
>    border-radius: 5px;
design system (round)

2023-04-16 22:05 UTC, simoncdn commented on src/components/reusableUI/TextInput.jsx
>        border-radius: 5px;
design system (round)

2023-04-17 10:20 UTC, YannLescot requested changes

2023-04-17 10:20 UTC, YannLescot commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/steph.ico" />
Ici je te propose plutôt de garder le favicon.ico et de le remplacer par ton image

2023-04-17 10:20 UTC, YannLescot commented on src/components/context/OrderContext.js
> +  setNewCard: () => {},
À quoi correspond setNewCard ? À l'affichage d'une nouvelle carte ? Ou d'un nouveau produit ? À un changement du menu ? À la création d'un nouveau style de card ?
En tant que collègue, j'aimerai ne pas avoir à aller vérifier ce qu'il en est dans ton code ... Dooonc ... Je te propose de trouver un naming qui ne laisse pas place au doute ! 💥

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/Admin/AdminPanel/AddForm.jsx
> +export const EMPTY_CARD = {
Attention au naming, à qui correspond cette variable ? À l'état d'une **carte** vide ? 🃏Ou bien à l'état d'un **produit** vide ? 🍔

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/OrderPage.jsx
> +      </OrderPageStyled>
Pourquoi as-tu une div "gb1-container" alors que tes éléments sont **déjà** enveloppés par OrderPageStyled ?

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/OrderPage.jsx
> +  const [newCard, setNewCard] = useState(EMPTY_CARD);
Est-ce que tu manipule une **carte** 🃏 ou un **produit** 🍔 ? Adapte ton naming (ici + OrderContext + chaque appel de ce state) en conséquence de ce que tu répondrai à cette question.

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/Admin/AdminPanel/SuccessMessage.jsx
> +}
Bonne idée d'en avoir fait un composant réutilisable, c'est pas mal non plus dans l'implémentation, mais si on parle du ticket F08 et de rien d'autre ... YAGNI 🐱‍👤

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/Admin/AdminPanel/AddForm.jsx
> +  price: "",
Devrais-tu initialiser price à une string vide alors que tu veux que price soit une int ?

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/Admin/AdminPanel/getInputTextConfig.js
> +    value: newCard.price ? newCard.price : "",
Attention à si tu change la valeur d'initialisation de "price" dans EMPTY-CARD, cette condition devra changer aussi

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/Admin/getTabsConfig.js
> +];
Tu as deux onClick tout à fait similaires qui prennent en paramètre un élément déjà présent dans ton objet ... Il y a un chouette moyen de retirer ces deux lignes d'ici pour n'en placer qu'une ailleurs, je te laisse y réfléchir 🙊

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/Basket.jsx
> +`
Pour le F08 ... YAGNI
AKA Dead code dans le cas où tu l'utilise nulle part

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/menu/EmptyMenuAdmin.jsx
> +      <MainButton label={"Générer de nouveaux produits"} onClick={onReset} className={"fontSet"} />
Quelle est la sorcellerie du nom de cette classname ? 🧙‍♂️
Tu n'es pas un sorcier, Stéphane !

2023-04-17 10:20 UTC, YannLescot commented on src/components/pages/order/main-content/menu/Menu.jsx
> +            imageSource={imageSource === "" ? "/images/coming-soon.png" : imageSource}
Cette string est magique ! 🌟✨
Je te propose de la stocker dans une variable plutôt que de l'entrer en dur ici.

2023-04-17 10:20 UTC, YannLescot commented on src/components/reusableUI/Card.jsx
> +          className="btnCart"
C'était "card" dans toute l'appli, pourquoi ça deviens "cart" ici ? Ton composant a goûté à la baguette ? 🥖

2023-04-17 10:20 UTC, YannLescot commented on src/components/reusableUI/MainButton.jsx
> +function MainButton({ ButtonIcon, label, className, onClick, version = "primary" }) {
Effectivement je ne suis pas sûr du renaming.
Un naming "MainButton" comme je le comprends, c'est LE bouton principal ( c'est ce que veux dire main d'ailleurs, là où primary c'est plus "léger" comme terme, et prompt à la réusabilité), qui n'est réutilisable que dans certains cas très précis, et pas partout comme nous nous le faisons dans l'appli.

2023-04-17 10:20 UTC, YannLescot commented on src/components/reusableUI/Tab.js
> +      <div className="Icon">{Icon}</div>
As-tu besoin d'une className si tu n'as qu'une div dans ton composant ? 🕊

2023-04-17 11:21 UTC, YannLescot commented on src/components/pages/order/main-content/Admin/AdminPanel/ImagePreviou.jsx
> +  const { newCard } = useContext(OrderContext);
Oh, et c'est "Preview", pas "Previou" :p

2023-04-18 12:59 UTC, closed without merging